import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vibhakar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="text-center mt-12 mb-5 bg-gray-50">
          <p className="text-sm text-gray-500">
            &copy; 2024 Vibhakar. All rights and wrongs are reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
